services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/ygo_db
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/target

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ygo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
